<a href="https://colab.research.google.com/github/YuriArduino/Words_Vectors/blob/main/Notebook/Word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vetorização de palavra

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

text= "/content/drive/MyDrive/Word_2_vec_Data/cbow_s300.txt"

modelo = KeyedVectors.load_word2vec_format(text)

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

text= "/content/drive/MyDrive/Word_2_vec_Data/cbow_s300.txt"

modelo = KeyedVectors.load_word2vec_format(text)

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

text= "/content/drive/MyDrive/Word_2_vec_Data/cbow_s300.txt"

modelo = KeyedVectors.load_word2vec_format(text)

In [1]:
import pandas as pd
import requests
import io


treino_url = 'https://media.githubusercontent.com/media/YuriArduino/Words_Vectors/refs/heads/main/Word_2_vec_Data/treino.csv'
teste_url = 'https://media.githubusercontent.com/media/YuriArduino/Words_Vectors/refs/heads/main/Word_2_vec_Data/teste.csv'

treino_url_content = requests.get(treino_url).content
teste_url_content = requests.get(teste_url).content

treino_df = pd.read_csv(io.StringIO(treino_url_content.decode('utf-8')))
teste_df = pd.read_csv(io.StringIO(teste_url_content.decode('utf-8')))

In [2]:
treino_df.head(5)

,title,text,date,category,subcategory,link
0,"Após polêmica, Marine Le Pen diz que abomina n...",A candidata da direita nacionalista à Presidên...,2017-04-28,mundo,NaN,http://www1.folha.uol.com.br/mundo/2017/04/187...
1,"Macron e Le Pen vão ao 2º turno na França, em ...",O centrista independente Emmanuel Macron e a d...,2017-04-23,mundo,NaN,http://www1.folha.uol.com.br/mundo/2017/04/187...
2,"Apesar de larga vitória nas legislativas, Macr...",As eleições legislativas deste domingo (19) na...,2017-06-19,mundo,NaN,http://www1.folha.uol.com.br/mundo/2017/06/189...
3,"Governo antecipa balanço, e Alckmin anuncia qu...",O número de ocorrências de homicídios dolosos ...,2015-07-24,cotidiano,NaN,http://www1.folha.uol.com.br/cotidiano/2015/07...
4,"Após queda em maio, a atividade econômica sobe...","A economia cresceu 0,25% no segundo trimestre,...",2017-08-17,mercado,NaN,http://www1.folha.uol.com.br/mercado/2017/08/1...

In [3]:
teste_df.head(5)

,title,text,date,category,subcategory,link
0,Grandes irmãos,"RIO DE JANEIRO - O Brasil, cada vez menos famí...",2017-03-06,colunas,ruycastro,http://www1.folha.uol.com.br/colunas/ruycastro...
1,Haddad congela orçamento e suspende emendas de...,"O prefeito de São Paulo, Fernando Haddad (PT),...",2016-08-10,colunas,monicabergamo,http://www1.folha.uol.com.br/colunas/monicaber...
2,Proposta de reforma da Fifa tem a divulgação d...,"A Fifa divulgou, nesta quinta (10), um relatór...",2015-10-09,esporte,NaN,http://www1.folha.uol.com.br/esporte/2015/09/1...
3,"Mercado incipiente, internet das coisas conect...","Bueiros, coleiras, aparelhos hospitalares, ele...",2016-11-09,mercado,NaN,http://www1.folha.uol.com.br/mercado/2016/09/1...
4,"Mortes: Psicanalista, estudou o autismo em cri...",Toda vez que o grupo de amigos de Silvana Rabe...,2017-02-07,cotidiano,NaN,http://www1.folha.uol.com.br/cotidiano/2017/07...

In [4]:
teste_df.iloc[643].title

'Somos todos imprevisíveis'

In [5]:
from sklearn.feature_extraction.text import CountVectorizer


texto =[
        "Tenha um bom dia",
        "Tenha um péssimo dia",
        "Tenha um otimo dia"
        ]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [6]:
print(vetorizador.vocabulary_)

{'tenha': 4, 'um': 5, 'bom': 0, 'dia': 1, 'péssimo': 3, 'otimo': 2}

In [7]:
vetor_bom = vetorizador.transform(["bom"])
print(vetor_bom.toarray())

[[1 0 0 0 0 0]]

In [11]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [12]:
from gensim.models import Word2Vec, KeyedVectors

text= "/content/drive/MyDrive/Word_2_vec_Data/cbow_s300.txt"

modelo = KeyedVectors.load_word2vec_format(text)

In [23]:
modelo.most_similar("freud")

[('jähn', 0.6199313402175903),
 ('romberg', 0.5987746119499207),
 ('an-ne-marie', 0.5902712345123291),
 ('anne-marie', 0.5618393421173096),
 ('deybel', 0.5361200571060181),
 ('wilmars', 0.5235167145729065),
 ('rascher', 0.5043884515762329),
 ('althusser', 0.45351576805114746),
 ('cara»,', 0.44022074341773987),
 ('wallice', 0.4345160722732544)]

In [31]:
modelo.most_similar(positive=["freud","psicanálise"])

[('criminologia', 0.5499325394630432),
 ('fenomenologia', 0.5352895259857178),
 ('romberg', 0.5283076167106628),
 ('sociologia', 0.526951253414154),
 ('ontologia', 0.5253108143806458),
 ('psicologia', 0.5126322507858276),
 ('antropologia', 0.5105752944946289),
 ('epistemologia', 0.5080766677856445),
 ('psiquiatria', 0.5040761232376099),
 ('cara»,', 0.4918973743915558)]

In [35]:
modelo.most_similar(positive=["freud","psicanálise"], negative= ["sociologia","fenomenologia"])

[('jähn', 0.37843307852745056),
 ('anne-marie', 0.3747199475765228),
 ('peixao', 0.3571247458457947),
 ('maximorespeito', 0.3562875986099243),
 ('deusnocontrole', 0.3551945388317108),
 ('romberg', 0.3471049666404724),
 ('deusnocomando', 0.3466319143772125),
 ('ressuscitá', 0.34302273392677307),
 ('an-ne-marie', 0.3376788794994354),
 ('todospelademocracia', 0.32821914553642273)]

In [ ]:
# 2. Definir o vetor de 300 dimensões que você deseja converter
# (Substitua pela sua variável de vetor)
meu_vetor = modelo['palavra']

# 3. Converter o vetor na palavra mais próxima
palavras_proximas = modelo.most_similar(positive=[meu_vetor], topn=1)

# 4. Extrair o texto da palavra ideal
palavra_convertida = palavras_proximas[0][0]
print(f"Texto correspondente: {palavra_convertida}")

In [38]:
import re

# Procura qualquer termo no vocabulário que contenha a raiz "freud"
padrao = re.compile(r'.*freud.*', re.IGNORECASE)
referencias_diretas = [p for p in modelo.index_to_key if padrao.match(p)]

print("Menções diretas encontradas no vocabulário:")
print(referencias_diretas)

Menções diretas encontradas no vocabulário:
['freud', 'freudiana', 'freudiano', 'freudenthal', 'freudianos', 'freudianas', 'freude', 'freudenberg', 'freudenstadt', 'schadenfreude', 'freudismo', 'freudianamente', 'freudienne', 'freudianismo', 'freudenthaler', 'freudenberger', 'freudenstein', 'freuds', 'freudo-marxismo', 'freudlose']

#Vetorização de texto

In [43]:
treino_df.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [45]:
import nltk
import string
# nltk.download('punkt')
# nltk.download('punkt_tab')

def tokenizador(texto):
  texto = texto.lower()
  lista_alfanumerico = []

  nltk.word_tokenize(texto)

  for token_valido in nltk.word_tokenize(texto):
    if token_valido in string.punctuation: continue
    lista_alfanumerico.append(token_valido)

  return lista_alfanumerico

tokenizador("Texto Exemplo, 1234.")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

['texto', 'exemplo', '1234']

In [49]:
import numpy as np

def combine_vectors(palavras_numeros):
  """Combina vetores por soma"""

  vetor_resultante = np.zeros(300)

  for pn in palavras_numeros:
    try:
      vetor_resultante += modelo.get_vector(pn)
    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo.get_vector(pn)
      else:
        vetor_resultante += modelo.get_vector("unknown")


  return vetor_resultante

In [50]:
palavras_numeros = tokenizador("texto 123")
vetor_texto = combine_vectors(palavras_numeros)
print(len(vetor_texto))
print(vetor_texto)

300
[-0.19017101  0.386951   -0.008594    0.30037799  0.159989   -0.101092
  0.43873099  0.270969   -0.161822    0.018511    0.64161899  0.127828
 -0.069744   -0.027795    0.124699   -0.119401   -0.28205699 -0.022199
  0.09366    -0.073118   -0.15385501  0.18351701 -0.16242101  0.03078201
  0.059678    0.22840899 -0.126967    0.28127    -0.228801   -0.051396
  0.42185001 -0.10387    -0.014022    0.048888    0.151869    0.1662
 -0.054594    0.56921098  0.017801    0.357465    0.052317    0.043465
  0.22348401 -0.084157    0.052653    0.104782    0.169336    0.062566
 -0.13132     0.221629    0.28166     0.43874899 -0.351202    0.223983
 -0.253742    0.148257   -0.18561     0.40756399  0.018232   -0.34813
 -0.15293301  0.206556    0.04577799 -0.35206901  0.309001   -0.012748
  0.37122799 -0.009942   -0.107348   -0.226903   -0.14168    -0.29536201
  0.09541     0.22013    -0.159844    0.10897    -0.27485    -0.230404
  0.066144   -0.313297    0.22517899 -0.076602    0.328972   -0.030489
  0.211367   -0.296988   -0.419711    0.169177    0.139838   -0.21745699
 -0.144137    0.063567    0.013596    0.22551301 -0.05122501 -0.236916
  0.071325    0.119615   -0.050565   -0.26064499  0.043027   -0.098988
  0.041467   -0.187247    0.174685   -0.080844    0.087869    0.046106
 -0.11787001  0.045911    0.266841    0.240149    0.36616799 -0.004325
  0.27162099 -0.18284101 -0.30138699  0.08452     0.061327    0.424293
  0.261332   -0.219944    0.278261    0.113077    0.126001   -0.545872
 -0.23498501  0.096669   -0.19967201  0.46199299  0.021795    0.04631899
 -0.012408    0.105149   -0.167694   -0.26432301  0.391792   -0.37025899
  0.42629801 -0.023128   -0.107421    0.247082   -0.29402399 -0.07855099
  0.004724    0.054975    0.170205    0.224723    0.33354199  0.16596201
 -0.181807    0.31107201  0.256465   -0.30056401  0.112293   -0.363465
  0.125632    0.12941     0.08988202  0.098047    0.087973   -0.140371
  0.15067399 -0.204957   -0.253184   -0.055962    0.186423    0.049263
 -0.153279   -0.093924   -0.140223   -0.164827    0.025717   -0.00798599
 -0.07012701 -0.146209    0.122932    0.22362599  0.139173   -0.078909
  0.22356299 -0.19916299  0.185269    0.17292399 -0.061412   -0.42691399
 -0.131291    0.12152401 -0.324971    0.43542899  0.175942    0.20854499
  0.042211   -0.173285   -0.025571    0.163129   -0.32653099 -0.59105198
 -0.00614499 -0.001415    0.40308    -0.37879701 -0.24280101  0.050652
 -0.209512   -0.024603   -0.158292    0.26444099 -0.13235501  0.394704
  0.148439   -0.21697399  0.202998    0.104241   -0.01859    -0.39457901
  0.170177   -0.26122    -0.29986801  0.00698     0.011245    0.136189
 -0.051582   -0.30661099  0.34229299 -0.240227   -0.044664   -0.218257
 -0.406766    0.093844   -0.052849   -0.14169599 -0.0016     -0.28894401
 -0.190898   -0.31971199 -0.187224   -0.22261801  0.026929   -0.307799
 -0.062257    0.29980999 -0.042293   -0.38094899  0.168193   -0.271326
  0.12420999 -0.054447    0.071321    0.13458    -0.389653   -0.032548
  0.27098201 -0.152093    0.157116   -0.001851    0.528061    0.08950299
 -0.033305   -0.31473999 -0.156932    0.100401   -0.087531   -0.26988401
 -0.28755701 -0.072797    0.44535099  0.002231    0.352552   -0.24986399
  0.262859    0.057585    0.15199199  0.294677   -0.132623   -0.20220001
  0.33808099 -0.06879299  0.14278501  0.134651    0.29133999 -0.04248
 -0.013569    0.425897    0.3974     -0.24125501  0.36309201 -0.79252401
 -0.314298   -0.15602699  0.29602899  0.152896    0.16037299 -0.019863
 -0.02959     0.22890599 -0.00308    -0.217078   -0.07042     0.40019101]